# Generated by Django 2.1.1 on 2018-09-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('singer', models.CharField(max_length=40)),
                ('type', models.CharField(blank=True, max_length=15, null=True)),
                ('mood', models.SmallIntegerField()),
                ('url', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'songlist',
                'managed': True,
            },
        ),
    ]
