# Generated by Django 2.1.1 on 2018-09-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='songlist',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
