# Generated by Django 2.1.1 on 2018-09-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_songlist_last_modified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('birth', models.DateField()),
                ('email', models.CharField(max_length=50)),
                ('job', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='songlist',
            options={'managed': False},
        ),
    ]
