# Generated by Django 2.1.1 on 2018-09-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20180929_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songlist',
            name='last_modified_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='songlist',
            name='mood',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='songlist',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='songlist',
            name='singer',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='songlist',
            name='type',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='songlist',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
