# Generated by Django 2.1.1 on 2018-10-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20180929_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='this_song_like_or_not',
            field=models.SmallIntegerField(null=True),
        ),
    ]
