# Generated by Django 2.1.1 on 2018-09-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=2)),
                ('email', models.CharField(max_length=200)),
                ('song', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('response', models.TextField()),
            ],
            options={
                'db_table': 'messages',
                'managed': True,
            },
        ),
    ]
