# Generated by Django 2.1.1 on 2018-10-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20180921_1654'),
        ('message', '0002_auto_20180922_2013'),
        ('message', '0003_merge_20180923_2149'),
    ]

    operations = [
    ]
