# Generated by Django 2.1.1 on 2018-10-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=2)),
                ('email', models.CharField(max_length=200)),
                ('song', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('response', models.TextField(blank='true')),
            ],
            options={
                'db_table': 'messages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Songlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('singer', models.CharField(max_length=45)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
                ('mood', models.IntegerField()),
                ('url', models.CharField(max_length=200)),
                ('last_modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'songlist',
            },
        ),
        migrations.CreateModel(
            name='Friends_Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberId', models.IntegerField()),
                ('messages', models.TextField()),
                ('messagesUpdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Friends_Chat',
            },
        ),
    ]
