# Generated by Django 2.1.1 on 2018-09-23 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_auto_20180922_1041'),
        ('donate', '0002_auto_20180921_0942'),
    ]

    operations = [
    ]
