# Generated by Django 2.1.1 on 2018-10-08 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0003_merge_20180923_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True},
        ),
    ]
