# Generated by Django 2.1.1 on 2018-10-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0004_merge_20181006_1501'),
        ('donate', '0004_merge_20181005_2048'),
    ]

    operations = [
    ]
