# Generated by Django 2.1.1 on 2018-10-08 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0005_merge_20181006_1908'),
        ('donate', '0004_merge_20181005_1839'),
    ]

    operations = [
    ]
