# Generated by Django 2.1.1 on 2018-10-08 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0004_auto_20181008_1713'),
        ('donate', '0006_merge_20181008_1127'),
    ]

    operations = [
    ]
