# Generated by Django 2.1.1 on 2018-09-20 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'managed': True},
        ),
    ]
