# Generated by Django 2.1.1 on 2018-10-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20180920_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='age',
        ),
        migrations.AddField(
            model_name='members',
            name='birthday',
            field=models.DateTimeField(default=1234, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='job',
            field=models.CharField(default=123, max_length=45),
            preserve_default=False,
        ),
    ]
