# Generated by Django 2.1.1 on 2018-09-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makefriends', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends_Chat',
            old_name='messages',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='friends_Chat',
            old_name='messagesUpdate',
            new_name='messageUpdate',
        ),
    ]
